### ISSUE TITLE
Error: Can't resolve 'app/plugins/sdk'

### ISSUE THREAD

**Issue by Trubochkin** [CorpGlory/grafana-plugin-template-webpack#4]
Во время сборки webpack ругается на графановские пути, что можно с этим сделать?

**Comment by Trubochkin** [comment]
Разобрался... нужно в импорте вместо app/ использовать garafana/

**Comment by Trubochkin** [comment]
Разобрался... нужно в импорте перед app/ добавить grafana/, полный импорт должен быть таким  `import { PanelCtrl } from 'grafana/app/plugins/sdk';`

**Comment by jonyrock** [comment]
@Trubochkin спасибо за коммент. Там как раз специально сделано так, что было `grafana/app` а не просто `app`. 
В конечном счете все компилится так, что импортируется уже как `app`
Вот кусок кода где это делается https://github.com/CorpGlory/grafana-plugin-template-webpack/blob/master/webpack.config.js#L18


As said @Trubochkin , you should write `import { PanelCtrl } from 'grafana/app/plugins/sdk'` instead of `import { PanelCtrl } from 'app/plugins/sdk'` which would for as you expect after compilation

**Comment by Trubochkin** [comment]
Спасибо, это я уже понял. Также пришлось ещё добавить extract-loader, css-loader, html-loader и file-loader. Рекомендую тоже добавить в шаблон:
      

```
      { 
        test: /\.css$/, 
        use: [ 'file-loader?name=[path][name].[ext]', 'extract-loader', 'css-loader' ]
      },
      {
        test: /\.html$/,
        use: [ 'file-loader?name=[path][name].[ext]', 'extract-loader', 'html-loader' ]
      },
      {
        test: /\.(svg|png|jpg|gif)$/,
        use: {
          loader: 'file-loader',
          options: {
            name: '[name].[ext]',
            outputPath: '/img/',
          },
        },
      },
```

**Comment by jonyrock** [comment]
@Trubochkin куль! Да пусть шаблон будем мелким. Спасибо

**Comment by jonyrock** [comment]
@Trubochkin давай тогда pull request сделаем ? :)

**Comment by Trubochkin** [comment]
Ok. A little later
