### ISSUE TITLE
Bundle node_modules

### ISSUE THREAD

**Issue by jmeberst** [CorpGlory/grafana-plugin-template-webpack#8]
Can this be used to bundle and import node modules installed through npm? I'm getting undefined errors in grafana when I try the following.

npm install underscore
npm run build

`...
import _ from 'underscore'
...
`

**Comment by jonyrock** [comment]
@jmeberst you definitely can do this. It was the reason to create the project. 

Give us a bit detailed error messages, please

**Comment by jmeberst** [comment]
I believe my issue is specific to importing underscore.

 I'm guessing this is because of the conflict with Grafana's lodash use of the '_' symbol, but it works if I import from a local library like /external/underscore. 

The error I'm getting is:

> Cannot read property '_' of undefined

**Comment by rozetko** [comment]
Hi @jmeberst! Thanks a lot for your feedback. 

Actually, this issue is not related to Grafana's lodash.

Currently we are working on fix. You can use a workaround for now:
Go to [build/webpack.base.conf](https://github.com/CorpGlory/grafana-plugin-template-webpack/blob/master/build/webpack.base.conf.js#L53) and change `exclude: /(external)/,` to `exclude: /node_modules|external/,`

P.S. See [this answer on SO](https://stackoverflow.com/a/39301850) for more information

**Comment by jmeberst** [comment]
That workaround solved it, thanks for making this plugin!

**Comment by rozetko** [comment]
@jmeberst you are welcome!
